### ISSUE TITLE
Script hangs

### ISSUE THREAD

**Issue by DmitrySokolov** [ValdikSS/blockcheck#24]
Exception in thread Thread-1:
    Traceback (most recent call last):
    File "C:\Dev\Tools\Python3\lib\threading.py", line 920, in _bootstrap_inner
      self.run()
    File "C:\Dev\Tools\Python3\lib\threading.py", line 868, in run
      self._target(*self._args, **self._kwargs)
    File "blockcheck.py", line 277, in main
      http = test_http_access(True)
    File "blockcheck.py", line 221, in test_http_access
      result_proxy = _get_url(site, proxy)
    File "blockcheck.py", line 135, in _get_url
      return (opened.status, str(opened.readall()))
    File "C:\Dev\Tools\Python3\lib\http\client.py", line 500, in read
      return super(HTTPResponse, self).read(amt)
    File "C:\Dev\Tools\Python3\lib\http\client.py", line 539, in readinto
      n = self.fp.readinto(b)
    File "C:\Dev\Tools\Python3\lib\socket.py", line 371, in readinto
      return self._sock.recv_into(b)
    socket.timeout: timed out

Script output:

    [O] Тестируем DNS
    [O] Получаем эталонные DNS с сервера
    	Эталонные адреса:		['104.28.16.79', '104.28.17.79', '5.178.68.100', '69.165.95.242', '78.110.160.185']
        	Адреса через системный DNS:	['10.52.34.222', '10.52.34.222', '10.52.34.222', '5.178.68.100']
    	Адреса через Google DNS:	['104.28.16.79', '104.28.17.79', '5.178.68.100', '69.165.95.242', '78.110.160.185']
    	Адреса через DNS AntiZapret:	['107.150.11.192', '107.150.11.192', '107.150.11.192', '107.150.11.192']
    [☠] DNS записи подменяются
    [✓] DNS не перенаправляется

    [O] Тестируем HTTP
    	Открываем http://gelbooru.com/index.php?page=post&s=view&id=1989610
    [☠] Сайт не открывается
    	Открываем http://gelbooru.com/
    [✓] Сайт открывается
    	Открываем http://sukebei.nyaa.se/?page=view&tid=395631
    [☠] Сайт не открывается
    	Открываем http://www.lostfilm.tv/
    [✓] Сайт открывается
    	Открываем http://sukebei.nyaa.se/
    [✓] Сайт открывается
    	Открываем http://www.lostfilm.tv/details.php?id=4141
    [✓] Сайт открывается
    	Открываем через прокси http://gelbooru.com/index.php?page=post&s=view&id=1989610
    [✓] Сайт открывается
    	Открываем через прокси http://gelbooru.com/
    [✓] Сайт открывается
    	Открываем через прокси http://sukebei.nyaa.se/?page=view&tid=395631
    [☠] Сайт не открывается
    	Открываем через прокси http://www.lostfilm.tv/
    [✓] Сайт открывается
    	Открываем через прокси http://sukebei.nyaa.se/

**Comment by DmitrySokolov** [comment]
Works now.
Thanks!
