### ISSUE TITLE
OSError(57, 'Socket is not connected')

### ISSUE THREAD

**Issue by Anakros** [ValdikSS/blockcheck#35]
Сабж при тестировании обхода DPI на OS X 10.11.3

```
[O] Тестируем обход DPI
	Пробуем способ: перенос строки в заголовках в UNIX-стиле
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: точка в конце домена
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: фрагментирование заголовка
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: заголовок host вместо Host
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: дополнительный пробел после GET
[☠] Ошибка:OSError(57, 'Socket is not connected')
```

В чём может быть дело?

**Comment by ValdikSS** [comment]
Приложите полный лог, пожалуйста.

**Comment by Anakros** [comment]
```
IP: x.x.x.x, провайдер: xxx

[O] Тестируем DNS
[O] Получаем эталонные DNS с сервера
	Эталонные адреса:		['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через системный DNS:	['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через Google DNS:	['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через DNS AntiZapret:	['107.150.11.192', '107.150.11.192', '107.150.11.192', '107.150.11.192']
[✓] DNS-записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем http://gelbooru.com/index.php?page=post&s=view&id=1989610
[☠] Сайт не открывается
	Открываем http://gelbooru.com/
[✓] Сайт открывается
	Открываем http://rule34.xxx/index.php?page=post&s=view&id=879177
[☠] Сайт не открывается
	Открываем http://rule34.xxx/
[✓] Сайт открывается
	Открываем через прокси http://gelbooru.com/index.php?page=post&s=view&id=1989610
[✓] Сайт открывается
	Открываем через прокси http://gelbooru.com/
[✓] Сайт открывается
	Открываем через прокси http://rule34.xxx/index.php?page=post&s=view&id=879177
[✓] Сайт открывается
	Открываем через прокси http://rule34.xxx/
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем https://e621.net/
[✓] Сайт открывается
	Открываем https://2chru.cafe/
[✓] Сайт открывается

[O] Тестируем обход DPI
	Пробуем способ: точка в конце домена
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: перенос строки в заголовках в UNIX-стиле
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: фрагментирование заголовка
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: заголовок host вместо Host
[☠] Ошибка:OSError(57, 'Socket is not connected')
	Пробуем способ: дополнительный пробел после GET
[☠] Ошибка:OSError(57, 'Socket is not connected')

[!] Результат:
[⚠] У вашего провайдера "обычный" DPI.
Вам поможет HTTPS/Socks прокси, VPN или Tor.
```

**Comment by ValdikSS** [comment]
Ваш провайдер не показывает заглушку, а разрывает соединение при посещении заблокированных URL?

**Comment by Anakros** [comment]
Нет, показывает заглушку. При посещении http://gelbooru.com/index.php?page=post&s=view&id=1989610, например.

**Comment by ValdikSS** [comment]
Есть ли у вас возможность предоставить мне удаленный доступ в вашу сеть или к вашему компьютеру? Напишите на iam@valdikss.org.ru (email или jabber), пожалуйста.

**Comment by Anakros** [comment]
Потестил в виртуалке на убунте в той же сети, всё окей. Значит что-то не так с макосью.

```
[O] Тестируем обход DPI
	Пробуем способ: точка в конце домена
[✓] Сайт открывается
	Пробуем способ: дополнительный пробел после GET
[✓] Сайт открывается
	Пробуем способ: фрагментирование заголовка
[✓] Сайт открывается
	Пробуем способ: перенос строки в заголовках в UNIX-стиле
[✓] Сайт открывается
	Пробуем способ: заголовок host вместо Host
[✓] Сайт открывается
```

**Comment by ValdikSS** [comment]
У меня, к сожалению, нет Mac, чтобы проверить. Было бы здорово, если бы вы нашли причину.

**Comment by Anakros** [comment]
Небольшой гуглёж и документация говорят, что socket.create_connection() возвращает слушающий сокет. Чтобы можно было в него писать/читать нужно сделать socket.accept() и использовать для данных возращаемую переменную.
У меня так падает с таймаутом, небольшой тест:
```
>>> import socket
>>> sock = socket.create_connection(("5.178.68.100", 80), 10)
>>> (conn, address) = sock.accept()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 195, in accept
    fd, addr = self._accept()
socket.timeout: timed out
```

Я не очень знаком с питоном и сокетами, если что. Файрвол соединение не блокирует, проверил скрипт на двух маках, ситуация одинакова.
Не ясно почему на линуксе всё работает.

**Comment by ValdikSS** [comment]
Да, вроде, нет, `accept()` служит для приема соединения, с create_connection именно подключается:

> Connect to a TCP service [which is] listening on the Internet address (a 2-tuple (host, port)), and return the socket object.

**Comment by Anakros** [comment]
Комментирую строчку `sock.shutdown(socket.SHUT_RDWR)` -- всё прекрасно работает.
Вот здесь такая же проблема https://bugs.launchpad.net/texttest/+bug/1170700
Собсно, патчик их вот такой: 
```
=== modified file 'lib/queuesystem/masterprocess.py'
--- lib/queuesystem/masterprocess.py	2013-02-27 09:57:11 +0000
+++ lib/queuesystem/masterprocess.py	2013-04-22 19:40:37 +0000
@@ -843,7 +843,11 @@
                     QueueSystemServer.instance.queueTestForRerun(test)
                 else:
                     self.server.changeState(test, state)
-                self.connection.shutdown(socket.SHUT_RD)
+                try:
+                    self.connection.shutdown(socket.SHUT_RD)
+                except socket.error, e:
+                    # This only occurs on a mac, and doesn't affect functionality.
+                    pass
                 if state.isComplete():
                     newTest = QueueSystemServer.instance.getTestForReuse(test, state, tryReuse)
                     if newTest:
```

**Comment by ValdikSS** [comment]
Попробуйте, пожалуйста.

**Comment by Anakros** [comment]
Всё окей.
