### ISSUE TITLE
Не запускается на Ubuntu 12.04

### ISSUE THREAD

**Issue by spvkgn** [ValdikSS/blockcheck#48]
```
/tmp/blockcheck-0.0.8.4 $ python3 ./blockcheck.py --console
Traceback (most recent call last):
  File "./blockcheck.py", line 10, in <module>
    import dns.resolver
  File "/usr/local/lib/python3.2/dist-packages/dns/resolver.py", line 33, in <module>
    import dns.ipv4
  File "/usr/local/lib/python3.2/dist-packages/dns/ipv4.py", line 34
    return (u'%u.%u.%u.%u' % (address[0], address[1],
                         ^
SyntaxError: invalid syntax
/tmp/blockcheck-0.0.8.4 $ python3 --version
Python 3.2.3
```

**Comment by ValdikSS** [comment]
Видимо, dnspython не поддерживает Python 3.2. Обновитесь хотя бы до 3.3, версия 3.2 очень старая.

**Comment by spvkgn** [comment]
ok, попробую. спасибо.
