### ISSUE TITLE
Установка на Mac

### ISSUE THREAD

**Issue by Nes-si** [ValdikSS/blockcheck#69]
Здравствуйте. Не дадите инструкцию по установке на Mac? Показывает только иконку в доке, не показывает окно. Вроде установил Tkinter (ActiveTcl8.5.18.0.298892).

**Comment by ValdikSS** [comment]
Вы пытаетесь установить из исходников? Собранная версия (zip-файл) должен работать без каких-либо зависимостей.

**Comment by Nes-si** [comment]
Нет, не из исходников, скачивал бинарник. 
Иконка висит в доке секунд 10, потом пропадает. Больше ничего.

**Comment by ValdikSS** [comment]
Нажмите на нее, она может быть свернута.

**Comment by Nes-si** [comment]
Естественно, я тыкал в нее, и многократно, и выбирал "Показать все окна" — эффект нулевой.
OS X 10.11.6.

**Comment by ValdikSS** [comment]
@zhovner

**Comment by Nes-si** [comment]
ну так что же?

**Comment by zhovner** [comment]
Попробуйте использовать актуальную версию macOS 10.12.

**Comment by Nes-si** [comment]
Прошу простить, но едва ли я буду менять систему ради возможности (не стопроцентной) запуска этой программы.

**Comment by ValdikSS** [comment]
@Nes-si, можете запустить blockcheck в консольном режиме, понадобится установленный Python 3 и зависимости из requirements.txt.

Я не знаю, почему у вас не работает программа, и не знаю, как это отладить. По всей видимости, у вас она выполняется, но не отображает графический интерфейс. Программа собирается на компьютере @zhovner, у него и еще у нескольких человек она работает.

**Comment by zhovner** [comment]
Какие у вас причины использовать устаревшую ОС?

**Comment by ValdikSS** [comment]
По всей видимости, при сборке программы через pyinstaller на новой версии macOS, не факт, что она будет запускаться на более старых версиях ОС.
Для сборки под macOS используется виртуальная машина @zhovner. Другой у меня нет.

**Comment by ilyjs** [comment]
zhovner Про устаревшую ОС.  
1) El Capitan это очень стабильная ОС. Это самая стабильная ось со времен snow leopard. Я начинал пользоваться маками со snow leopard.  
2) Если вы просто обновитесь то можете получить дополнительные проблемы и глюки я не раз их получал, по этому предпочтительно делать чистую установку, а это займет много времени. Прийдется все ставить и настраивать снова.

**Comment by zhovner** [comment]
> El Capitan это очень стабильная ОС. Это самая стабильная ось 

В чем проявляется нестабильность актуальных версий macOS? Нет никакой причины пользоваться устаревшими ОС на устройствах apple.

**Comment by alex-connor** [comment]
> предпочтительно делать чистую установку, а это займет много времени. Прийдется все ставить и настраивать снова

не сказал бы, что этот процесс занимает так много времени... да, и если вы боитесь устанавливать все программы заново, то для вас есть Time Machine, который все бекапит и потом восстанавливает без всяких проблем

**Comment by ilyjs** [comment]
zhovner Я благодарен вам за то что вы собираете исходники на  мак ос , а те у кого не актуальная версия системы сами виноваты . Давайте не устраивать холивар. Я запустил из исходников все работает. Собрал в pyinstaller под El Capitan , не открывается окно, но консольная версия запускается и работает. Это проблемы ос , я это признаю. 
alex-connor  спасибо за совет.  
Я очень благодарен ValdikSS за прогу . Билайн заблочил  https://robomongo.org/ это инструмент управления mongoDB и material-ui-next.com это скажем так бета дока по библиотеке react компонентов. Билайн блочит именно по ip. 
Я попробую собрать на маке под py2app в выходные и отпишусь тут.

**Comment by ilyjs** [comment]
И так я пробовал собирать в py2app и cx_freeze. И все это успехом не кончилось. 
Что я могу сказать. В сборке pyinstaller появляется и консольная версия приложения. Она у меня работает. Так, что в релиз можно класть еще и консольную версию для устройств до сиеры.

**Comment by egocentrist** [comment]
В информации о релизе [Blockcheck v0.0.9.6](https://github.com/ValdikSS/blockcheck/releases/tag/0.0.9.6), отсутствует ссылка на бинарник для mac, хотя она упоминается в тексте.

**Comment by Infestedd** [comment]
UPD ^^
В информации о релизе Blockcheck v0.0.9.6, отсутствует ссылка на бинарник для mac, хотя она упоминается в тексте.

**Comment by ValdikSS** [comment]
Как только мне предоставят виртуальную машину с macOS, я соберу blockcheck и выложу его.

**Comment by ValdikSS** [comment]
Добавлен релиз для macOS.

**Comment by John998** [comment]
Каким образом можно собрать аппликуху под Мак?

**Comment by ValdikSS** [comment]
@John998, установите [pyinstaller](https://www.pyinstaller.org/), запустите `pyinstaller blockcheck.spec`

**Comment by John998** [comment]
@ValdikSS 

> MacBook-Air-Vladislav% pyinstaller blockcheck.spec
> 63 INFO: PyInstaller: 3.3.1
> 63 INFO: Python: 2.7.10
> 114 INFO: Platform: Darwin-17.4.0-x86_64-i386-64bit
> 149 INFO: UPX is not available.
> 226 INFO: Extending PYTHONPATH with paths
> ['/Users/john/Downloads/blockcheck-master']
> 226 INFO: checking Analysis
> 227 INFO: Building Analysis because out00-Analysis.toc is non existent
> 227 INFO: Initializing module dependency graph...
> 256 INFO: Initializing module graph hooks...
> 316 INFO: running Analysis out00-Analysis.toc
> 322 INFO: Caching module hooks...
> 326 INFO: Analyzing blockcheck.py
> 
> Syntax error in blockcheck.py
>   File "/Users/john/Downloads/blockcheck-master/blockcheck.py", line 215
>      def print(*args, **kwargs):
>              ^
>  SyntaxError: invalid syntax

И начиная с 215-ой blockcheck.py

> def print(*args, **kwargs):
>     global printed_text, printed_text_with_debug
>     if tkusable:
>         this_text = print_string(*args, **kwargs)
>         text.write(this_text)
>         printed_text += this_text
>         printed_text_with_debug += this_text
>     else:
>         if args and sys.stdout.encoding != 'UTF-8':
>             args = [x.translate(trans_table).replace("[☠]", "[FAIL]").replace("[☺]", "[:)]"). \
>                     encode(sys.stdout.encoding, 'replace').decode(sys.stdout.encoding) for x in args
>                    ]
>         __builtins__.print(*args, **kwargs)
>         this_text = print_string(*args, **kwargs)
>         printed_text += this_text
>         printed_text_with_debug += this_text

**Comment by ValdikSS** [comment]
Нужен Python 3, а не 2.

**Comment by John998** [comment]
@ValdikSS 

> MacBook-Air-Vladislav% cd /Users/john/Downloads/blockcheck-master/             
> MacBook-Air-Vladislav% pyinstaller blockcheck.spec
> 172 INFO: PyInstaller: 3.3.1
> 172 INFO: Python: 3.6.5
> 264 INFO: Platform: Darwin-17.4.0-x86_64-i386-64bit
> 292 INFO: UPX is not available.
> 403 INFO: Extending PYTHONPATH with paths
> ['/Users/john/Downloads/blockcheck-master']
> 403 INFO: checking Analysis
> 404 INFO: Building Analysis because out00-Analysis.toc is non existent
> 404 INFO: Initializing module dependency graph...
> 406 INFO: Initializing module graph hooks...
> 408 INFO: Analyzing base_library.zip ...
> 5543 INFO: running Analysis out00-Analysis.toc
> 5635 INFO: Caching module hooks...
> 5640 INFO: Analyzing blockcheck.py
> 6264 INFO: Loading module hooks...
> 6265 INFO: Loading module hook "hook-_tkinter.py"...
> 6329 INFO: checking Tree
> 6329 INFO: Building Tree because out00-Tree.toc is non existent
> 6329 INFO: Building Tree out00-Tree.toc
> 6358 INFO: checking Tree
> 6358 INFO: Building Tree because out01-Tree.toc is non existent
> 6358 INFO: Building Tree out01-Tree.toc
> 6372 INFO: Loading module hook "hook-_tkinter.py"...
> 6400 INFO: checking Tree
> 6400 INFO: Building Tree because out02-Tree.toc is non existent
> 6400 INFO: Building Tree out02-Tree.toc
> 6415 INFO: checking Tree
> 6416 INFO: Building Tree because out03-Tree.toc is non existent
> 6416 INFO: Building Tree out03-Tree.toc
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pyinstaller", line 11, in <module>
>     load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
>     exec(text, spec_namespace)
>   File "<string>", line 36, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
>     self.__postinit__()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
>     self.assemble()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 472, in assemble
>     module_hook.post_graph()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 414, in post_graph
>     self._process_hook_func()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 433, in _process_hook_func
>     self._hook_module.hook(hook_api)
>   File "/Users/john/Downloads/blockcheck-master/osx_hooks/hook-_tkinter.py", line 245, in hook
>     hook_api.add_datas(_collect_tcl_tk_files(hook_api))
>   File "/Users/john/Downloads/blockcheck-master/osx_hooks/hook-_tkinter.py", line 229, in _collect_tcl_tk_files
>     _warn_if_activetcl_or_teapot_installed(tcl_root, tcltree)
>   File "/Users/john/Downloads/blockcheck-master/osx_hooks/hook-_tkinter.py", line 65, in _warn_if_activetcl_or_teapot_installed
>     from PyInstaller.lib.macholib import util
> **ModuleNotFoundError: No module named 'PyInstaller.lib.macholib'**

**Comment by ValdikSS** [comment]
Видимо, в новой версии pyinstaller что-то изменили, возможно, исправили старые ошибки, для которых нужны были хуки. Уберите их из spec-файла.

**Comment by John998** [comment]
@ValdikSS 

Вроде бы как все хорошо, но аппликуха не запускается. Логов по программе нету.

> MacBook-Air-Vladislav% pyinstaller blockcheck.spec
> 5405 INFO: PyInstaller: 3.3.1
> 5405 INFO: Python: 3.6.5
> 5968 INFO: Platform: Darwin-17.4.0-x86_64-i386-64bit
> 5977 INFO: UPX is not available.
> 7583 INFO: Extending PYTHONPATH with paths
> ['/Users/john/Downloads/blockcheck-master']
> 7584 INFO: checking Analysis
> 7584 INFO: Building Analysis because out00-Analysis.toc is non existent
> 7584 INFO: Initializing module dependency graph...
> 7642 INFO: Initializing module graph hooks...
> 7670 INFO: Analyzing base_library.zip ...
> 13542 INFO: running Analysis out00-Analysis.toc
> 13569 INFO: Caching module hooks...
> 13573 INFO: Analyzing blockcheck.py
> 15740 INFO: Loading module hooks...
> 15741 INFO: Loading module hook "hook-_tkinter.py"...
> 15758 INFO: checking Tree
> 15758 INFO: Building Tree because out00-Tree.toc is non existent
> 15758 INFO: Building Tree out00-Tree.toc
> 15779 INFO: checking Tree
> 15779 INFO: Building Tree because out01-Tree.toc is non existent
> 15779 INFO: Building Tree out01-Tree.toc
> 15789 INFO: Loading module hook "hook-dns.rdata.py"...
> 16307 INFO: Loading module hook "hook-encodings.py"...
> 16417 INFO: Loading module hook "hook-pydoc.py"...
> 16420 INFO: Loading module hook "hook-xml.dom.domreg.py"...
> 16421 INFO: Loading module hook "hook-xml.py"...
> 16445 INFO: Looking for ctypes DLLs
> 16445 INFO: Analyzing run-time hooks ...
> 16449 INFO: Including run-time hook 'pyi_rth__tkinter.py'
> 16476 INFO: Looking for dynamic libraries
> 16763 INFO: Looking for eggs
> 16763 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.6/Python
> 16766 INFO: Warnings written to /Users/john/Downloads/blockcheck-master/build/blockcheck/warnblockcheck.txt
> 16811 INFO: Graph cross-reference written to /Users/john/Downloads/blockcheck-master/build/blockcheck/xref-blockcheck.html
> 16838 INFO: Appending 'datas' from .spec
> 16878 INFO: checking PYZ
> 16878 INFO: Building PYZ because out00-PYZ.toc is non existent
> 16878 INFO: Building PYZ (ZlibArchive) /Users/john/Downloads/blockcheck-master/build/blockcheck/out00-PYZ.pyz
> 17337 INFO: Building PYZ (ZlibArchive) /Users/john/Downloads/blockcheck-master/build/blockcheck/out00-PYZ.pyz completed successfully.
> 17349 INFO: checking PKG
> 17349 INFO: Building PKG because out00-PKG.toc is non existent
> 17349 INFO: Building PKG (CArchive) out00-PKG.pkg
> 23557 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
> 23572 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
> 23572 INFO: checking EXE
> 23572 INFO: Building EXE because out00-EXE.toc is non existent
> 23572 INFO: Building EXE from out00-EXE.toc
> 23573 INFO: Appending archive to EXE /Users/john/Downloads/blockcheck-master/dist/blockcheck
> 23682 INFO: Fixing EXE for code signing /Users/john/Downloads/blockcheck-master/dist/blockcheck
> 23848 INFO: Building EXE from out00-EXE.toc completed successfully.
> 23863 INFO: checking BUNDLE
> 23863 INFO: Building BUNDLE because out00-BUNDLE.toc is non existent
> 23863 INFO: Building BUNDLE out00-BUNDLE.toc
> 23904 INFO: moving BUNDLE data files to Resource directory

**Comment by ilyjs** [comment]
@John998 Какая версия ОС у вас?

**Comment by Sogl** [comment]
@ValdikSS 

Не запускается на Sierra 10.12.6 (у меня Hackintosh).
![image](https://user-images.githubusercontent.com/7556290/58387981-d1e0f300-8020-11e9-9ba1-c7a3705ba672.png)

Полный crash report выложил тут: https://gist.github.com/Sogl/f1a606d4b0656911f451cebd8376d9b7
