### ISSUE TITLE
Cant install the requirements

### ISSUE THREAD

**Issue by GGGunrunner** [ValdikSS/blockcheck#76]
Raspbian
uname -a
Linux 4.14.42-v7+ #1114 SMP Mon May 21 16:39:21 BST 2018 armv7l GNU/Linux

python3 -m pip install -r requirements.txt

Downloading/unpacking dnspython (from -r requirements.txt (line 1))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 292, in find_requirement
    elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
  File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
  File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in <listcomp>
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /root/.pip/pip.log

:(

**Comment by ValdikSS** [comment]
What python version do you have?

**Comment by ValdikSS** [comment]
Do you still have problems with installing?

**Comment by ValdikSS** [comment]
No reply, closing.
